-- Use SQL insert statements to add any
-- starting/dummy data to your database tables

-- EXAMPLE:

--  insert into "todos"
--    ("task", "isCompleted")
--    values
--      ('Learn to code', false),
--      ('Build projects', false),
--      ('Get a job', false);

INSERT INTO "products" (
  "name", "price", "description", "minPlayers", "maxPlayers", "imageUrl", "primaryPublisher", "primaryDesigner")
  VALUES ('Catan', 47.99, 'The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too.To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea.Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!', 3, 4, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629324722072.jpg', 'Catan Studio', 'Klaus Teuber'),
  ('Monopoly Deal Card Game', 7.99, 'Get a handy way to play the classic property-trading game! Be the first collect 3 full property sets of different colors, and you''ll win the Monopoly Deal Card Game. You''ll pick up cards when it''s your turn and play Action cards to charge players rent, steal their cards or demand money for your birthday. Build up property sets, gather piles of money and keep wheeling and dealing until you''re the Monopoly Deal winner!', 2, 5, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559255820851-51PyKtxYE9L.jpg', 'Parker Brothers', 'Katharine Chapman'),
  ('Bananagrams', 12.99, 'Addictively simple, and simply addictive, BANANAGRAMS is the fast and frantic word game enjoyed by millions! Players and their opponents aim to use all of their letters to build a word grid in a race to the finish. The first player to use all of their tiles is crowned ''Top Banana''! BANANAGRAMS requires no pencil, paper, or board, and comes in a small portable banana-shaped pouch that''s perfect for ages 7 and up —at home or on the go.', 1, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257788549-4190ktYkAjL.jpg', 'Bananagrams, Inc.', 'Rena Nathanson'),
  ('Scrabble', 19.92, 'The classic word-on-word showdown. Use your letters to score points and challenge your family and friends. A double or triple letter or word space will let you earn big points. It''s your word against theirs!', 2, 4, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1599599554926', 'Hasbro', 'Alfred Mosher Butts'),
  ('Unstable Unicorns', 14.49, 'A strategic card game that will destroy your friendships...but in a good way. One of Kickstarter''s Top 50 Most Backed Projects of all time! Build a Unicorn Army. Betray your friends. Unicorns are your friends now.', 2, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1541531739549', 'Breaking Games', 'Ramy Badie'),
  ('Codenames', 12.81, 'The two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their CODENAMES. The teams compete to see who can make contact with all of their agents first. Spymasters give one-word clues that can point to multiple words on the board. Their teammates try to guess words of the right color while avoiding those that belong to the opposing team. And everyone wants to avoid the assassin. Codenames: win or lose, it''s fun to figure out the clues.', 2, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/userfiles/1679240870315-codenames_masked.png', 'Czech Games Edition', 'Vlaada Chvátil'),
  ('Blokus', 19.99, 'Stake your claim and protect your territory with the Blokus game! It takes less than a minute to learn, but offers endless strategy and fun challenges for the whole family. Each player gets a set of 21 pieces - in red, blue, green, or yellow - then takes turns placing them on the board. There''s just one rule: each piece you play must touch at least one other piece of the same color, but only at the corners! The goal is to fit the most pieces on the board. The game ends when no more pieces can be placed down, and the player with the lowest number remaining wins!', 2, 4, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1590173343841', 'Mattel', 'Bernard Tavitian'),
  ('Connect Four', 8.99, 'Drop your red or yellow discs in the grid and be the first to get 4 in a row to win. If your opponent is getting too close to 4 in a row, block them with your own disc. Whoever wins can pull out the slider bar to release all the discs and start the fun all over again.', 2, 2, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200327-61eEJMGY3YL.jpg', 'Milton Bradley', 'Howard Wexler'),
  ('Rummikub', 15.00, 'Players take turns placing numbered tiles in runs (consecutive numbers of the same color) and groups (three or more of the same number in different colors), Rummy style. The board continually changes as players adjust the tiles on the table. The Joker tiles add to the fun and can be played as any color or number. Be the first player to play every tile on your rack to win! Rummikub includes 106 high quality plastic tiles, 4 plastic tile-holder racks, and complete illustrated instructions.', 2, 4, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254849801-61DrzE6DaPL.jpg', 'Pressman Toy Corp.', 'Ephraim Hertzano'),
  ('Candy Land', 8.99, 'Classic board game of adventure and sweet surprises. Each player advances along the rainbow path through the peppermint stick forest, the gingerbread plum tree and the gumdrop mountain. If you are the first person to reach the last purple space, or move beyond the last purple space, you reach candy castle and have won the game. Contents: gameboard, 4 movers, 44 cards, and instructions. In the 2004 version, younger players are not required to remove backward on the track if they draw a named card, and the last square of the track was changed from a Violet Square to a Rainbow Square, resolving a 55-year dispute over whether a player needs to land on the Violet Square or move beyond the Violet Square to win. Prior to the 2006 version, three colored spaces on the track (one in Molasses Swamp and two Cherry Pitfalls) were marked with a dot. Players who landed on a dot were "stuck", and were unable to move from the spot until they drew a card that matched the color of the square they were on. The 2006 version replaced gum drops with licorice spaces; players who land on a licorice space only lose their next turn. 65th Anniversary Edition: This classic edition features the charming graphics and components from the game''s early days! Celebrating over 65 years of great family fun! Bi-fold heavy-duty gameboard, 4 plastic gingerbread men movers Deck of 64 cards Instructions including “The Story Of Candy Land.', 2, 4, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257915124-61Q9oYi-RSL.jpg', 'Hasbro', 'Eleanor Abbott'),
  ('Battleship', 12.99, 'Battleship is the classic game of head-to-head naval combat. Players search for the enemy''s fleet of ships and destroy them one by one. Each player announces the coordinates of each strike, and sees if it hits. Players command a powerful fleet that includes an aircraft carrier, a destroyer, a submarine, a patrol boat, and a battleship. Position ships strategically to survive opponent''s relentless strikes, and track hits and misses with red and white pegs on the ocean grid. No ship is safe in this game of stealth and suspense.', 2, 2, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254873443-51Sf8HSbPHL.jpg', 'Parker Brothers', 'Clifford Von Wickler'),
  ('Monopoly', 14.99, 'The thrill of bankrupting an opponent, the possibility of playing a 9 hour game, and the absolution between winning and losing, could change with the roll of the dice. Experience the ups and downs by collecting property color''s sets to build houses, and hopefully upgrading to a hotel. But don''t play just for certain colors, or else your opponent may change their strategy. The more properties each player owns, the more rent can be charged, but trading is where the game can help you, or hurt you. So, be wise! Chance cards could be worth money, like $10 for winning second place in a beauty pageant or sending you to “Go” for an extra $200; but you might just get the one that says, “Go To Jail”. Buy, Sell, Dream and Scheme to Win it All! Turn a debt into an ultimate victory!', 2, 8, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1609460299342', 'Hasbro', 'Charles Darrow'),
  ('Chess', 12.99, 'Chess is a game for two players on an 8x8 grid with alternating light and dark spaces. Each player has a matching set of 16 pieces, including 8 pawns, 2 rooks, 2 knights, 2 bishops, a queen, and a king. Each type of piece has its own rules for movement. The object of the game is to capture the opponent''s king.', 2, 2, 'https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1594689503033', '', '');

INSERT INTO "featuredProducts" ("productId")
  VALUES (1),
         (2),
         (3),
         (4),
         (5);
